# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trainer_api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trainer_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11trainer_api.proto\" \n\rActionRequest\x12\x0f\n\x07gba_key\x18\x01 \x01(\x05\"7\n\x0bObservation\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x14\n\x0cis_exploring\x18\x02 \x01(\x08\x32\x32\n\nTrainerApi\x12$\n\x04Step\x12\x0e.ActionRequest\x1a\x0c.ObservationB\x0f\xaa\x02\x0c\x41iPlays.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trainer_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\014AiPlays.Grpc'
  _globals['_ACTIONREQUEST']._serialized_start=21
  _globals['_ACTIONREQUEST']._serialized_end=53
  _globals['_OBSERVATION']._serialized_start=55
  _globals['_OBSERVATION']._serialized_end=110
  _globals['_TRAINERAPI']._serialized_start=112
  _globals['_TRAINERAPI']._serialized_end=162
# @@protoc_insertion_point(module_scope)
